server:
  port: 8082 # Port ri�ng cho Product Service

spring:
  application:
    name: product-service
  url:
    blockchain-service: http://localhost:8083/api/v1/blockchain/history
  datasource:
    url: jdbc:postgresql://localhost:5433/product_db
    username: admin
    password: password123 # Thay b?ng pass c?a b?n
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
