services:
  # Database chính cho hệ thống
  postgres-db:
    image: postgres:15
    container_name: traceability-postgres
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password123
      POSTGRES_DB: identity_db # DB đầu tiên cho Identity Service
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./postgres/init:/docker-entrypoint-initdb.d:ro
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U admin -d identity_db" ]
      interval: 10s
      timeout: 5s
      retries: 10

  # Công cụ quản lý DB trực quan qua trình duyệt
  pgadmin:
    image: dpage/pgadmin4
    container_name: traceability-pgadmin
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@kma.edu.vn
      PGADMIN_DEFAULT_PASSWORD: admin
    depends_on:
      postgres-db:
        condition: service_healthy

  # Bộ nhớ đệm cho hiệu năng cao
  redis-cache:
    image: redis:7-alpine
    container_name: traceability-redis
    ports:
      - "6379:6379"
  # Message Broker cho Event-Driven Architecture (Kafka KRaft)
  kafka:
    image: apache/kafka:latest
    container_name: traceability-kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_LISTENERS: PLAINTEXT://:9092,CONTROLLER://:9093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@localhost:9093
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_NUM_PARTITIONS: 1

volumes:
  postgres_data: