# Cau hinh Server
server.port=8083
spring.application.name=blockchain-service

# Cau hinh Web3j (Ket noi Ganache)
# Thay 7545 bang cong ban thay tren Ganache
web3j.client-address=http://127.0.0.1:7545

# Cau hinh Vi (Nguoi se tra phi gas de ghi du lieu)
# Dan Private Key ban vua copy vao day
blockchain.wallet.private-key=0xf4a4bcbab54312d462c50ee3057ca471aa44e9736715e28cfad9801b3a9e16bb

# Dia chi Contract (Luc dau de trong, sau khi Deploy xong thi dien vao)
blockchain.contract.address=0xa2bd5292d16885b34f52924457244ad11fe3a82f

# Cau hinh Gas (Phi giao dich - de mac dinh the nay la on cho Ganache)
blockchain.gas.limit=12000000
blockchain.gas.price=20000000000